//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRC_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Riesgo()
        {
            this.Tratamientos = new HashSet<Tratamiento>();
        }
    
        public int IdRiesgo { get; set; }
        public int IdActivo { get; set; }
        public string Amenaza { get; set; }
        public string Vulnerabilidad { get; set; }
        public int Probabilidad { get; set; }
        public int Impacto { get; set; }
        public Nullable<int> NivelRiesgo { get; set; }
        public Nullable<bool> Tratado { get; set; }
    
        public virtual Activo Activo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamiento> Tratamientos { get; set; }
    }
}
