//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRC_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public int IdTratamiento { get; set; }
        public int IdRiesgo { get; set; }
        public string Estrategia { get; set; }
        public string AccionCorrectiva { get; set; }
        public string Responsable { get; set; }
        public Nullable<System.DateTime> FechaLimite { get; set; }
        public Nullable<int> Progreso { get; set; }
    
        public virtual Riesgo Riesgo { get; set; }
    }
}
