//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRC_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TratamientoKPI
    {
        public int IdKPI { get; set; }
        public int IdTratamiento { get; set; }
        public string NombreKPI { get; set; }
        public string MetaEsperada { get; set; }
        public string FrecuenciaMedicion { get; set; }
    
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
