//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGRC_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TratamientoBitacora
    {
        public int IdBitacora { get; set; }
        public int IdTratamiento { get; set; }
        public Nullable<int> IdKPI { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string DescripcionActividad { get; set; }
        public string UsuarioResponsable { get; set; }
        public string ObservacionesTecnicas { get; set; }
    
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
